---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: i18n
  label: i18n
  create: all
  match: "**/*"
- type: directory
  path: data
  label: data
  create: all
  match: "**/*"
- type: directory
  path: content
  label: content
  create: all
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: content/ru/top-news
  label: Top-News [RU]
  create: all
  match: "**/*"
- type: directory
  path: content/**/news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: content/**/youtube
  label: YouTube
  create: all
  match: "**/*"
- type: directory
  path: content/**/begginers
  label: Полезное
  create: all
  match: "**/*"
- type: directory
  path: content/**/articles
  label: Статьи
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
