---
label: base
hide_body: false
fields:
- type: text
  name: author
  label: author
- type: list
  name: cat
  label: cat
- type: datetime
  name: date
  label: date
- type: file
  name: img
  label: img
- type: list
  name: tags
  label: tags
- type: text
  name: title
  label: title
- type: boolean
  name: top
  label: top
- type: text
  name: type
  label: type
